# Generated by Django 5.0.7 on 2024-08-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_hit',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
