# Generated by Django 5.0.7 on 2025-04-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='password_hit',
            new_name='password_hint',
        ),
    ]
