services:
  web:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: cryptkeeper_web
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./static:/app/static
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    networks:
      - cryptkeeper

  db:
    image: postgres:15
    container_name: cryptkeeper_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - cryptkeeper

networks:
  cryptkeeper:

volumes:
  db_data:
