services:
  web:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: cryptkeeper_web
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - cryptkeeper
      - proxy-net

  db:
    image: postgres:15
    container_name: cryptkeeper_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - cryptkeeper

networks:
  cryptkeeper:
  proxy-net:
    external: true

volumes:
  db_data:
